// Export helpers: findings (CSV/JSON) and Volatility dump shell scripts.
// All generation is client-side; downloads use Blob + object URLs so the app
// works fully offline (file://) as well as when served from the backend.
import type { Finding, PagecacheFile } from "@/models";

function download(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const csvCell = (v: unknown): string => {
  const s = v == null ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function findingsToCsv(findings: Finding[]): string {
  const header = ["level", "rule", "technique", "target", "detail", "mitre"];
  const lines = [header.join(",")];
  for (const f of findings) {
    const mitre = (f.mitre ?? []).map((m) => m.id).join(" ");
    lines.push(
      [f.level, f.rule, f.technique ?? "", f.target, f.detail, mitre]
        .map(csvCell)
        .join(",")
    );
  }
  return lines.join("\n");
}

export function exportFindings(findings: Finding[], fmt: "csv" | "json"): void {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  if (fmt === "json") {
    download(`findings-${stamp}.json`, JSON.stringify(findings, null, 2), "application/json");
  } else {
    download(`findings-${stamp}.csv`, findingsToCsv(findings), "text/csv");
  }
}

/** Build a `vol ... InodePages --inode <InodeAddr> --dump` command for one file. */
export function dumpCommand(file: PagecacheFile, image: string): string {
  const addr = file.inodeAddr?.trim();
  if (addr) {
    return `vol -f ${image} linux.pagecache.InodePages --inode ${addr} --dump`;
  }
  // Fallback to path-based extraction when the address column is absent.
  return `vol -f ${image} linux.pagecache.InodePages --find "${file.filePath}" --dump`;
}

/** Emit a runnable bash script that dumps every supplied pagecache file. */
export function exportDumpScript(files: PagecacheFile[], image: string): void {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const lines = [
    "#!/usr/bin/env bash",
    "# Generated by DumpHound — Volatility 3 page-cache extraction",
    "# NOTE: --inode takes the InodeAddr (address), NOT the InodeNum.",
    "set -euo pipefail",
    "mkdir -p ./dumped",
    "",
  ];
  for (const f of files) {
    lines.push(`# ${f.filePath}`);
    if (f.inodePages && f.cachedPages && f.cachedPages < f.inodePages) {
      lines.push(
        `#  partial cache: ${f.cachedPages}/${f.inodePages} pages present (output will be zero-padded)`
      );
    }
    lines.push(`${dumpCommand(f, image)}`);
    lines.push("");
  }
  lines.push("# Bulk filesystem reconstruction (alternative):");
  lines.push(`# vol -o ./dumped -f ${image} linux.pagecache.RecoverFs`);
  download(`dump-pagecache-${stamp}.sh`, lines.join("\n"), "text/x-shellscript");
}
